### ISSUE TITLE
Process 'quick entries' on behalf of other users

### ISSUE THREAD

**Issue by slimcdk** [akhilrex/hammond#22]
Hi! 
I would like to be able to mark who had the expense when processing them from the quick entires menu.

My gf is interested in using the app as long as she can just upload the image. I'm willing to process all our entries, but I would rather not sign into her user when processing her expenses, but instead just mark the expense as belonging to her.

**Comment by akhilrex** [comment]
Sharing quickentries could have over share vehicles but that would have meant that you had to choose the vehicle as well when making the quick entry. That would not really go well the "quickness" of the process.

I would recommend that you guys use a single common login instead of having 2 separate logins. This would be much easier for you guys to manage.

**Comment by akhilrex** [comment]
Please ignore my last comment. I had misread your commend. This is already in pipeline.

**Comment by akhilrex** [comment]
Please rebuild your container once this build finishes and this should work for you.
